# Unset all possible IPF config vars

unset BASE_DIR
unset CITY
unset COMPUTE_INTERVAL
unset COUNTRY
unset ENVIRONMENT
unset IGNORE_TOPLEVEL_MODULEFILES
unset LATITUDE
unset LMOD_CACHE_FILE
unset LONGITUDE
unset MODULEPATH
unset MODULES
unset MODULES_EXCLUDE
unset MODULES_INTERVAL
unset MODULES_RECURSE
unset ORGANIZATION_NAME
unset PBS_LOG_DIR
unset PUBLISH
unset RESOURCE_NAME
unset SCHEDULER
unset SCHEDULER_PARAMS
unset SERVICEPATH
unset SERVICES_INTERVAL
unset SGE_REPORTING_LOG
unset SLURMCTL_LOG
unset SUPPORT_CONTACT
unset WORKFLOWS
unset WORKFLOWTEMPLATE
